DROP TABLE IF EXISTS weather.load_temp;
CREATE UNLOGGED TABLE weather.load_temp (doc JSON);
COPY weather.load_temp from '{{ params.file }}' ;
INSERT INTO weather.daily_api_local (queryCost,
                                        latitude,
                                        longitude,
                                        resolvedAddress,
                                        address,
                                        timezone,
                                        tzoffset,
                                        datetime,
                                        datetimeEpoch,
                                        tempmax,
                                        tempmin,
                                        feelslikemax,
                                        feelslikemin,
                                        feelslike,
                                        dew,
                                        humidity,
                                        precip,
                                        precipprob,
                                        precipcover,
                                        preciptype,
                                        snow,
                                        snowdepth,
                                        windgust,
                                        windspeed,
                                        winddir,
                                        pressure,
                                        cloudcover,
                                        visibility,
                                        solarradiation,
                                        solarenergy,
                                        uvindex,
                                        severerisk,
                                        sunrise,
                                        sunriseEpoch,
                                        sunset,
                                        sunsetEpoch,
                                        moonphase,
                                        conditions,
                                        description,
                                        icon,
                                        station)

SELECT (doc->>'queryCost')::INT AS queryCost,
                (doc->>'latitude') AS latitude,
                (doc->>'longitude') AS longitude,
                (doc->>'resolvedAddress') AS resolvedAddress,
                (doc->>'address') AS "address",
                (doc->>'timezone') AS timezone,
                (doc->>'tzoffset')::DOUBLE PRECISION AS tzoffset,
                (doc->'days'->0->>'datetime')::DATE AS "datetime",
                (doc->'days'->0->>'datetimeEpoch')::NUMERIC  AS datetimeEpoch,
                (doc->'days'->0->>'tempmax')::DOUBLE PRECISION AS tempmax,
                (doc->'days'->0->>'tempmin')::DOUBLE PRECISION AS tempmin,
                (doc->'days'->0->>'feelslikemax')::DOUBLE PRECISION AS feelslikemax,
                (doc->'days'->0->>'feelslikemin')::DOUBLE PRECISION AS feelslikemin,
                (doc->'days'->0->>'feelslike')::DOUBLE PRECISION AS feelslike,
                (doc->'days'->0->>'dew')::DOUBLE PRECISION AS dew,
                (doc->'days'->0->>'humidity')::DOUBLE PRECISION AS humidity,
                (doc->'days'->0->>'precip')::DOUBLE PRECISION AS precip,
                (doc->'days'->0->>'precipprob')::DOUBLE PRECISION AS precipprob,
                (doc->'days'->0->>'precipcover')::DOUBLE PRECISION AS precipcover,
                (doc->'days'->0->>'preciptype')::TEXT AS preciptype,
                (doc->'days'->0->>'snow')::DOUBLE PRECISION AS snow,
                (doc->'days'->0->>'snowdepth')::DOUBLE PRECISION AS snowdepth,
                (doc->'days'->0->>'windgust')::DOUBLE PRECISION AS windgust,
                (doc->'days'->0->>'windspeed')::DOUBLE PRECISION AS windspeed,
                (doc->'days'->0->>'winddir')::DOUBLE PRECISION AS winddir,
                (doc->'days'->0->>'pressure')::DOUBLE PRECISION AS pressure,
                (doc->'days'->0->>'cloudcover')::DOUBLE PRECISION AS cloudcover,
                (doc->'days'->0->>'visibility')::DOUBLE PRECISION AS visibility,
                (doc->'days'->0->>'solarradiation')::DOUBLE PRECISION AS solarradiation,
                (doc->'days'->0->>'solarenergy')::DOUBLE PRECISION AS solarenergy,
                (doc->'days'->0->>'uvindex')::DOUBLE PRECISION AS uvindex,
                (doc->'days'->0->>'severerisk')::DOUBLE PRECISION AS severerisk,
                (doc->'days'->0->>'sunrise') AS sunrise,
                (doc->'days'->0->>'sunriseEpoch')::NUMERIC AS sunriseEpoch,
                (doc->'days'->0->>'sunset') AS sunset,
                (doc->'days'->0->>'sunsetEpoch')::NUMERIC AS sunsetEpoch,
                (doc->'days'->0->>'moonphase')::DOUBLE PRECISION AS moonphase,
                (doc->'days'->0->>'conditions') AS conditions,
                (doc->'days'->0->>'description') AS description,
                (doc->'days'->0->>'icon') AS icon,
                (doc->'days'->'stations')::JSON as stations
                FROM weather.load_temp;