INSERT INTO weather.f_hist SELECT rdhl.id,
                                  CAST(latitude AS DOUBLE PRECISION),
                                  CAST(longitude AS DOUBLE PRECISION),
                                  time,
                                  tavg,
                                  tmin,
                                  tmax,
                                  prcp,
                                  snow,
                                  wdir,
                                  wspd,
                                  wpgt,
                                  pres,
                                  tsun
                                FROM weather.raw_daily_historic_local rdhl
                                LEFT JOIN weather.dim_location l ON TRIM(UPPER(split_part(rdhl.add, ',', 1))) = TRIM(UPPER(l.address))
                                WHERE NOT EXISTS (SELECT m_id FROM weather.f_hist WHERE m_id = rdhl.id);

INSERT INTO weather.f_daily SELECT id,
                                CAST(latitude AS DOUBLE PRECISION),
                                CAST(longitude AS DOUBLE PRECISION),
                                datetime, 
                                tempmax, 
                                tempmin, 
                                feelslikemax,
                                feelslikemin, 
                                feelslike,
                                dew,
                                humidity,
                                precip,
                                precipprob,
                                precipcover,
                                preciptype,
                                snow,
                                snowdepth,
                                windgust,
                                windspeed,
                                winddir,
                                pressure,
                                cloudcover,
                                visibility,
                                solarradiation,
                                solarenergy,
                                uvindex,
                                severerisk,
                                sunrise,
                                sunset,
                                moonphase,
                                conditions,
                                description 
                            FROM weather.raw_daily_api_local rdal 
                            WHERE NOT EXISTS ( SELECT d_id FROM weather.f_daily WHERE d_id = rdal.id);