
-- WITH weather_daily_local (doc) AS (VALUES(
-- '
-- [
--     {
--         "queryCost": 1,
--         "latitude": 32.4492,
--         "longitude": -99.7414,
--         "resolvedAddress": "Abilene, TX, United States",
--         "address": "Abilene",
--         "timezone": "America/Chicago",
--         "tzoffset": -5.0,
--         "days": [
--             {
--                 "datetime": "2022-10-15",
--                 "datetimeEpoch": 1665810000,
--                 "tempmax": 87.7,
--                 "tempmin": 66.8,
--                 "temp": 76.6,
--                 "feelslikemax": 88.2,
--                 "feelslikemin": 66.8,
--                 "feelslike": 76.9,
--                 "dew": 59.9,
--                 "humidity": 57.4,
--                 "precip": 0.0,
--                 "precipprob": 0.0,
--                 "precipcover": 0.0,
--                 "preciptype": null,
--                 "snow": 0.0,
--                 "snowdepth": 0.0,
--                 "windgust": 31.3,
--                 "windspeed": 19.6,
--                 "winddir": 166.5,
--                 "pressure": 1010.9,
--                 "cloudcover": 4.3,
--                 "visibility": 9.9,
--                 "solarradiation": 158.9,
--                 "solarenergy": 13.7,
--                 "uvindex": 5.0,
--                 "severerisk": 75.0,
--                 "sunrise": "07:42:49",
--                 "sunriseEpoch": 1665837769,
--                 "sunset": "19:06:08",
--                 "sunsetEpoch": 1665878768,
--                 "moonphase": 0.65,
--                 "conditions": "Clear",
--                 "description": "Clear conditions throughout the day.",
--                 "icon": "clear-day",
--                 "stations": [
--                     "KDYS",
--                     "KCOM",
--                     "HBYT2",
--                     "KSWW",
--                     "TWB39",
--                     "KABI"
--                 ],
--                 "source": "obs"
--             }
--         ],
--         "stations": {
--             "KDYS": {
--                 "distance": 10709.0,
--                 "latitude": 32.42,
--                 "longitude": -99.85,
--                 "useCount": 0,
--                 "id": "KDYS",
--                 "name": "KDYS",
--                 "quality": 98,
--                 "contribution": 0.0
--             },
--             "KCOM": {
--                 "distance": 75063.0,
--                 "latitude": 31.84,
--                 "longitude": -99.4,
--                 "useCount": 0,
--                 "id": "KCOM",
--                 "name": "KCOM",
--                 "quality": 97,
--                 "contribution": 0.0
--             },
--             "HBYT2": {
--                 "distance": 13005.0,
--                 "latitude": 32.5,
--                 "longitude": -99.617,
--                 "useCount": 0,
--                 "id": "HBYT2",
--                 "name": "HAMBY TX US",
--                 "quality": 0,
--                 "contribution": 0.0
--             },
--             "KSWW": {
--                 "distance": 68475.0,
--                 "latitude": 32.47,
--                 "longitude": -100.47,
--                 "useCount": 0,
--                 "id": "KSWW",
--                 "name": "KSWW",
--                 "quality": 100,
--                 "contribution": 0.0
--             },
--             "TWB39": {
--                 "distance": 72386.0,
--                 "latitude": 31.825,
--                 "longitude": -99.957,
--                 "useCount": 0,
--                 "id": "TWB39",
--                 "name": "Winton Milliff Runnells TX US TWDB",
--                 "quality": 0,
--                 "contribution": 0.0
--             },
--             "KABI": {
--                 "distance": 6622.0,
--                 "latitude": 32.42,
--                 "longitude": -99.68,
--                 "useCount": 0,
--                 "id": "KABI",
--                 "name": "KABI",
--                 "quality": 100,
--                 "contribution": 0.0
--             }
--         }
--     }
-- ]
-- '::json)
-- ), expand AS (
--   SELECT json_array_elements(doc) AS doc
--    FROM weather_daily_local
-- )
-- INSERT INTO weather_daily_local (queryCost, latitude, longitude, resolvedAddress, address, timezone, tzoffset, datetime, datetimeEpoch, tempmax, tempmin, feelslikemax, feelslikemin, feelslike, dew, humidity, precip, precipprob, precipcover, preciptype, snow, snowdepth, windgust, windspeed, winddir, pressure, cloudcover, visibility, solarradiation, solarenergy, uvindex, severerisk, sunrise, sunriseEpoch, sunset, sunsetEpoch, moonphase, conditions, description, icon, station)
-- SELECT (doc->>'queryCost')::INT AS queryCost,
-- 	(doc->>'latitude') AS latitude,
--     (doc->>'longitude') AS longitude,
-- 	(doc->>'resolvedAddress') AS resolvedAddress,
-- 	(doc->>'address') AS "address",
-- 	(doc->>'timezone') AS timezone,
-- 	(doc->>'tzoffset')::DOUBLE PRECISION AS tzoffset,
-- 	(doc->'days'->0->>'datetime')::DATE AS "datetime",
-- 	(doc->'days'->0->>'datetimeEpoch')::INT AS datetimeEpoch,
--     (doc->'days'->0->>'tempmax')::DOUBLE PRECISION AS tempmax,
-- 	(doc->'days'->0->>'tempmin')::DOUBLE PRECISION AS tempmin,
-- 	(doc->'days'->0->>'feelslikemax')::DOUBLE PRECISION AS feelslikemax,
-- 	(doc->'days'->0->>'feelslikemin')::DOUBLE PRECISION AS feelslikemin,
-- 	(doc->'days'->0->>'feelslike')::DOUBLE PRECISION AS feelslike,
-- 	(doc->'days'->0->>'dew')::DOUBLE PRECISION AS dew,
-- 	(doc->'days'->0->>'humidity')::DOUBLE PRECISION AS humidity,
-- 	(doc->'days'->0->>'precip')::DOUBLE PRECISION AS precip,
-- 	(doc->'days'->0->>'precipprob')::DOUBLE PRECISION AS precipprob,
-- 	(doc->'days'->0->>'precipcover')::DOUBLE PRECISION AS precipcover,
-- 	(doc->'days'->0->>'preciptype') AS preciptype,
-- 	(doc->'days'->0->>'snow')::DOUBLE PRECISION AS snow,
-- 	(doc->'days'->0->>'snowdepth')::DOUBLE PRECISION AS snowdepth,
-- 	(doc->'days'->0->>'windgust')::DOUBLE PRECISION AS windgust,
-- 	(doc->'days'->0->>'windspeed')::DOUBLE PRECISION AS windspeed,
-- 	(doc->'days'->0->>'winddir')::DOUBLE PRECISION AS winddir,
-- 	(doc->'days'->0->>'pressure')::DOUBLE PRECISION AS pressure,
-- 	(doc->'days'->0->>'cloudcover')::DOUBLE PRECISION AS cloudcover,
-- 	(doc->'days'->0->>'visibility')::DOUBLE PRECISION AS visibility,
-- 	(doc->'days'->0->>'solarradiation')::DOUBLE PRECISION AS solarradiation,
-- 	(doc->'days'->0->>'solarenergy')::DOUBLE PRECISION AS solarenergy,
-- 	(doc->'days'->0->>'uvindex')::DOUBLE PRECISION AS uvindex,
-- 	(doc->'days'->0->>'severerisk')::DOUBLE PRECISION AS severerisk,
-- 	(doc->'days'->0->>'sunrise') AS sunrise,
-- 	(doc->'days'->0->>'sunriseEpoch')::DOUBLE PRECISION AS sunriseEpoch,
-- 	(doc->'days'->0->>'sunset') AS sunset,
-- 	(doc->'days'->0->>'sunsetEpoch')::DOUBLE PRECISION AS sunsetEpoch,
-- 	(doc->'days'->0->>'moonphase')::DOUBLE PRECISION AS moonphase,
-- 	(doc->'days'->0->>'conditions') AS conditions,
-- 	(doc->'days'->0->>'description') AS description,
-- 	(doc->'days'->0->>'icon') AS icon,
-- 	(doc->'days'->'stations')::JSON as stations
-- FROM expand;
  